server:
  port: 8085

springdoc:
  api-docs:
    path: /api/notifications/v3/api-docs

spring:
  main:
    banner-mode: off
  application:
    name: notification-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/db_notification}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000 # 24h
