package com.floodrescue.shared.exception;

import org.springframework.http.HttpStatus;

import lombok.Getter;

@Getter
public enum ErrorCode {

    // ===== CHUNG =====
    UNAUTHORIZED("UNAUTHORIZED", HttpStatus.UNAUTHORIZED),
    FORBIDDEN("FORBIDDEN", HttpStatus.FORBIDDEN),
    NOT_FOUND("NOT_FOUND", HttpStatus.NOT_FOUND),
    VALIDATION_ERROR("VALIDATION_ERROR", HttpStatus.BAD_REQUEST),
    INTERNAL_ERROR("INTERNAL_ERROR", HttpStatus.INTERNAL_SERVER_ERROR),

    // ===== AUTH =====
    DUPLICATE_PHONE("DUPLICATE_PHONE", HttpStatus.CONFLICT),
    DUPLICATE_EMAIL("DUPLICATE_EMAIL", HttpStatus.CONFLICT),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS", HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN("INVALID_TOKEN", HttpStatus.UNAUTHORIZED),
    ACCOUNT_INACTIVE("ACCOUNT_INACTIVE", HttpStatus.FORBIDDEN),

    // ===== RESCUE REQUEST =====
    REQUEST_NOT_FOUND("REQUEST_NOT_FOUND", HttpStatus.NOT_FOUND),
    REQUEST_ALREADY_ACTIVE("REQUEST_ALREADY_ACTIVE", HttpStatus.BAD_REQUEST),
    REQUEST_INVALID_STATUS("REQUEST_INVALID_STATUS", HttpStatus.BAD_REQUEST),
    REQUEST_FORBIDDEN("REQUEST_FORBIDDEN", HttpStatus.FORBIDDEN),

    // ===== DISPATCH =====
    TEAM_NOT_FOUND("TEAM_NOT_FOUND", HttpStatus.NOT_FOUND),
    TEAM_UNAVAILABLE("TEAM_UNAVAILABLE", HttpStatus.CONFLICT),
    ASSIGNMENT_NOT_FOUND("ASSIGNMENT_NOT_FOUND", HttpStatus.NOT_FOUND),
    ASSIGNMENT_INVALID_STATUS("ASSIGNMENT_INVALID_STATUS", HttpStatus.BAD_REQUEST),
    REQUEST_ALREADY_ASSIGNED("REQUEST_ALREADY_ASSIGNED", HttpStatus.CONFLICT),
    VEHICLE_UNAVAILABLE("VEHICLE_UNAVAILABLE", HttpStatus.CONFLICT),

    // ===== RESOURCE =====
    WAREHOUSE_NOT_FOUND("WAREHOUSE_NOT_FOUND", HttpStatus.NOT_FOUND),
    ITEM_NOT_FOUND("ITEM_NOT_FOUND", HttpStatus.NOT_FOUND),
    INSUFFICIENT_STOCK("INSUFFICIENT_STOCK", HttpStatus.CONFLICT),
    VEHICLE_NOT_FOUND("VEHICLE_NOT_FOUND", HttpStatus.NOT_FOUND),
    DUPLICATE_PLATE_NUMBER("DUPLICATE_PLATE_NUMBER", HttpStatus.CONFLICT),

    // ===== NOTIFICATION =====
    SSE_SEND_FAILED("SSE_SEND_FAILED", HttpStatus.INTERNAL_SERVER_ERROR);

    private final String code;
    private final HttpStatus httpStatus;

    ErrorCode(String code, HttpStatus httpStatus) {
        this.code = code;
        this.httpStatus = httpStatus;
    }
}